### ISSUE TITLE
DatasetInfo: Submit button doesn't work without Preview 

### ISSUE THREAD

**Issue by maria-grigorieva** [PanDAWMS/InVEx#82]
If we click on Submit without clicking Preview before, it doesn't work. 
Here I see 2 options: 
- show Submit only after Preview was clicked
- reimplement Submit button

**Comment by mtitov** [comment]
Branches "dataset-handling-refactoring" and "clustering-dimensions" includes corresponding update. Buttons "Preview" and "Submit" works the same, except that Submit-button actually finalizes the feature selection process and moves forward for further analysis
